# Site info
title: BAI Data Analysis Intro
author: Nicolas Behrens
email: nicolas.behrens@uni-muenster.de
description: >
On this page we will explore some methods of data analysis in ecophysiology in R

# Build Settings
markdown: kramdown
theme: minima
plugins:
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
