# Site info
title: BAI Data Analysis Intro
author: Nicolas Behrens
email: nicolas.behrens@uni-muenster.de
description: On this page we will explore some methods of data analysis in ecophysiology in R
show_excerpts: true

header-pages:
  - 2023-01-05-Exercise1RBasics.md
  - 2023-01-05-Exercise2Plotting.md
  - 2023-01-05-Exercise3Interpolation.md
  - 2023-01-04-Exercise4ExtremeDetection.md

# Build Settings
markdown: kramdown
theme: minima
plugins:
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
