# Site info
title: BAI Data Analysis Intro
author: Nicolas Behrens
email: nicolas.behrens(at)uni-muenster.de
show_excerpts: true

header-pages:
  - Exercise1RBasics.md
  - Exercise2Plotting.md
  - Exercise3Interpolation.md
  - Exercise4ExtremeDetection.md

# Build Settings
markdown: kramdown
theme: minima
plugins:
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
